trigger:
- master


jobs:
- job: A
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: |
      export SHELL=/bin/bash
      export MOZCONFIG="$(pwd)/mozconfig"
      export CFLAGS="-march=btver1 -mtune=btver1 -O3"
      export CXXFLAGS="-march=btver1 -mtune=btver1 -O3"
      export RUSTFLAGS="-Copt-level=3 -Ctarget-cpu=btver1"
      echo $MOZCONFIG
      wget -q https://ftp.mozilla.org/pub/firefox/releases/69.0.1/source/firefox-69.0.1.source.tar.xz
      tar -xf firefox*
      rm *.xz
      mv firefox* source
      cd source
      sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
      sudo sh -c "echo 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main' >> /etc/apt/sources.list"
      sudo add-apt-repository ppa:jonathonf/nasm
      sudo apt-get -qq update
      sudo apt-get -qq install lld-9 clang-9 clang++-9 libllvm9 llvm-9 llvm-9-dev nasm autoconf2.13 build-essential nodejs python-dev python-pip python-setuptools unzip uuid zip
      sudo apt-get -qq install libpulse-dev libasound2-dev libcurl4-openssl-dev libdbus-1-dev libdbus-glib-1-dev libgtk-3-dev libgtk2.0-dev libpulse-dev libx11-xcb-dev libxt-dev python-dbus xvfb yasm
      sudo ln -sf /usr/bin/clang-9 /usr/bin/clang
      sudo ln -sf /usr/bin/clang++-9 /usr/bin/clang++
      ./mach build
      ls firefox-build-dir
      ./mach package
      ls firefox-build-dir/dist

      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'build firefox'

  - task: CopyFiles@2
    inputs:
      SourceFolder: /home/vsts/work/1/s/source/firefox-build-dir/dist
      contents: '**'
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: GitHubRelease@0
    inputs:
      action: create
      gitHubConnection: for-firefox-release
      repositoryName: santouits/firefox-builder
      tagSource: manual
      tag: $(Build.BuildNumber)
      addChangeLog: false
      assets: $(Build.ArtifactStagingDirectory)/**
    displayName: 'create_github_release'
