trigger:
- master


jobs:
- job: A
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: |
      echo "RAM"
      free -h
      echo "disks"
      df -h
      echo "root directory"
      ls /

      df -h .
      df -Ph . | tail -1 | awk '{print $4}'
      ls /sys/cgroups

      echo "Starting script"
      ###swap
      #sudo mkdir -p /mnt/resource
      #sudo fallocate -l 15g /mnt/resource/swap15g
      #sudo chmod 600 /mnt/resource/swap15g
      #sudo mkswap /mnt/resource/swap15g
      #sudo swapon /mnt/resource/swap15g
      #cat /proc/swaps
      #free -h
      #df -h

      # Install build tools and dependencies
      wget -q https://ftp.mozilla.org/pub/firefox/releases/69.0.1/source/firefox-69.0.1.source.tar.xz
      tar -xf firefox*
      rm *.xz
      mv firefox* source
      cd source
      sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
      #sudo sh -c "echo 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main' >> /etc/apt/sources.list"
      sudo add-apt-repository ppa:jonathonf/nasm
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      sudo apt-get -qq update
      #sudo apt-get -qq install g++-9 lld-9 clang-9 clang++-9 libllvm9 llvm-9 llvm-9-dev nasm autoconf2.13 build-essential nodejs python-dev python-pip python-setuptools unzip uuid zip
      sudo apt remove mono* *firefox* *chrome* *chromium* *google* *android*
      sudo apt autoremove
      sudo apt-get -qq install g++-9 nasm autoconf2.13 build-essential nodejs python-dev python-pip python-setuptools unzip uuid zip
      sudo apt-get -qq install libpulse-dev libasound2-dev libcurl4-openssl-dev libdbus-1-dev libdbus-glib-1-dev libgtk-3-dev libgtk2.0-dev libpulse-dev libx11-xcb-dev libxt-dev python-dbus xvfb yasm

      #sudo ln -sf /usr/bin/clang-9 /usr/bin/clang
      #sudo ln -sf /usr/bin/clang++-9 /usr/bin/clang++
      #sudo ln -sf /usr/bin/llvm-ar-9 /usr/bin/ar
      #sudo ln -sf /usr/bin/llvm-ranlib-9 /usr/bin/ranlib

      sudo ln -sf /usr/bin/gcc-9 /usr/bin/gcc
      sudo ln -sf /usr/bin/g++-9 /usr/bin/g++
      #sudo ln -sf /usr/bin/gcc-ar-9 /usr/bin/gcc-ar
      #sudo ln -sf /usr/bin/gcc-nm-9 /usr/bin/gcc-nm
      #sudo ln -sf /usr/bin/gcc-ranlib-9 /usr/bin/gcc-ranlib
      sudo ln -sf /usr/bin/gcc-ar-9 /usr/bin/ar
      #sudo ln -sf /usr/bin/gcc-nm-9 /usr/bin/nm
      sudo ln -sf /usr/bin/gcc-ranlib-9 /usr/bin/ranlib

      # Set environment variables
      export SHELL=/bin/bash
      export MOZCONFIG="$(pwd)/../mozconfig"
      echo $MOZCONFIG
      #export CFLAGS="-march=btver1 -mtune=btver1 -O3"
      #export CXXFLAGS="-march=btver1 -mtune=btver1 -O3"
      #export LDFLAGS="-march=btver1 -mtune=btver1 -O3"
      #export RUSTFLAGS="-Copt-level=3 -Ctarget-cpu=btver1"
      #export CARGO_RUSTCFLAGS="-Copt-level=3 -Ctarget-cpu=btver1"
      export CC=gcc
      export CXX=g++
      #export RANLIB=gcc-ranlib
      #export NM=gcc-nm

      ./mach build
      ls firefox-build-dir
      ./mach package
      ls firefox-build-dir/dist

      free -h
      df -h

    displayName: 'build firefox'

  - task: CopyFiles@2
    inputs:
      SourceFolder: /home/vsts/work/1/s/source/firefox-build-dir/dist
      contents: '*.tar.bz2'
      targetFolder: $(Build.ArtifactStagingDirectory)

      #- task: GitHubRelease@0
      #inputs:
      #action: create
      #gitHubConnection: for-firefox-release
      #repositoryName: santouits/firefox-builder
      #tagSource: manual
      #tag: $(Build.BuildNumber)
      #addChangeLog: false
      #assets: $(Build.ArtifactStagingDirectory)/**
      #displayName: 'create_github_release'
