# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    export SHELL=/bin/bash
    export MOZCONFIG="$(pwd)/mozconfig"
    export CFLAGS="-march=native -mtune=native -O3"
    export CXXFLAGS="-march=native -mtune=native -O3"
    echo $MOZCONFIG
    wget -q https://ftp.mozilla.org/pub/firefox/releases/69.0.1/source/firefox-69.0.1.source.tar.xz
    tar -xf firefox*
    rm *.xz
    mv firefox* source
    ls
    cd source
    sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
    sudo sh -c "echo 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main' >> /etc/apt/sources.list"
    sudo add-apt-repository ppa:jonathonf/nasm
    sudo apt remove clang clang++
    sudo apt-get update
    sudo apt-get build-dep firefox
    sudo apt-get install lld-9 clang-9 clang++-9 libllvm9 llvm-9 llvm-9-dev nasm autoconf2.13 build-essential nodejs python-dev python-pip python-setuptools unzip uuid zip
    sudo apt-get install libpulse-dev libasound2-dev libcurl4-openssl-dev libdbus-1-dev libdbus-glib-1-dev libgtk-3-dev libgtk2.0-dev libpulse-dev libx11-xcb-dev libxt-dev python-dbus xvfb yasm
    sudo ln -sf /usr/bin/clang-9 /usr/bin/clang
    sudo ln -sf /usr/bin/clang++-9 /usr/bin/clang++
    ./mach build

    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
